name: Build

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Format files
        run: yarn run format

      - name: Fix ESLint errors
        run: yarn run lint --fix

      - name: Run Build
        run: yarn run build