
name: Deploy RAEL to SSH Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to SSH server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          #   key: ${{ secrets.SSH_PRIVATE_KEY }}
          # fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            cd ~/apps/rcamis/rael
            git stash
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm i -g yarn
            yarn install
            chmod +x scripts/create_env.sh
            ./scripts/create_env.sh
            yarn run build
            pm2 restart rael